base_url = "https://atelier-anchor.com"

title = "atelierAnchor"
description = "atelierAnchor is a design studio based in Shanghai with an edge on crafts and technology."

compile_sass = true
# minify_html = true
build_search_index = false

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
[extra.author_aliases]
client = "CL"
creative_director = "CD"
art_director = "AD"
type_director = "TD"
designer = "D"
publisher = "P"
translator = "T"
editor = "E"
