base_url = "https://atelier-anchor.com"

title = "atelierAnchor"
description = "graphic & typeface design studio in shanghai. we make typeface as A narrative."

compile_sass = true
# minify_html = true
build_search_index = false

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
generator = "Zola 0.14.1"
address = [
    "15A, Lane 141",
    "Xing'an Road",
    "Huangpu District",
    "Shanghai, China",
    "[hi@atelier-anchor.com](mailto:hi@atelier-anchor.com)",
    "[twitter](https://twitter.com/atelier_anchor) [instagram](https://www.instagram.com/atelier_anchor)",
]
author_aliases = [
    { name = "client",            alias = "CL" },
    { name = "author",            alias = "A"  },
    { name = "translator",        alias = "T"  },
    { name = "chief-editor",      alias = "CE" },
    { name = "editor",            alias = "E"  },
    { name = "creative-director", alias = "CD" },
    { name = "art-director",      alias = "AD" },
    { name = "type-director",     alias = "TD" },
    { name = "designer",          alias = "D"  },
    { name = "publisher",         alias = "P"  },
]
